In [210]:
# importing libraries
import requests
from bs4 import BeautifulSoup
from pprint import pprint
import pandas as pd

#Pulling the html code from ev-database.org electric cars webpage

url='https://ev-database.org/#sort:path~type~order=.rank~number~desc|range-slider-range:prev~next=0~1200|range-slider-acceleration:prev~next=2~23|range-slider-topspeed:prev~next=110~450|range-slider-battery:prev~next=10~200|range-slider-towweight:prev~next=0~2500|range-slider-fastcharge:prev~next=0~1500|paging:currentPage=0|paging:number=all'

data=requests.get(url)

# Creating an empty list to hold the data

ev_data=[]

# Creating a variable to hold the scraped data

html = BeautifulSoup(data.text, 'html.parser')

#creating a variable to allow structuring of data using html containers and class names

evcars = html.select('div.list-item')

# iterating through evcars to scrape the desired data using class names to identify relevant data

for evcar in evcars:
    
    make = evcar.select('.title')[0].get_text()
    model = evcar.select('.model')[0].get_text()
    battery_Kwh = evcar.select('.battery')[0].get_text()
    acceleration = evcar.select('.acceleration')[0].get_text()
    top_speed = evcar.select('.topspeed')[0].get_text()
    erange_real = evcar.select('.erange_real')[0].get_text()
    efficiency = evcar.select('.efficiency')[0].get_text()
    price_in_de = evcar.select('.country_de')[0].get_text()
    
    #adding the data to ev_data
    
    ev_data.append({"Make": make, "Model": model, "Battery_(Kwh)": battery_Kwh, "Acceleration_in_Secs_(1-100)": acceleration,
                    "Top_Speed_(km/h)": top_speed, "Range_(km)": erange_real, "Efficiency_(Wh/km)": efficiency, "Price_in_Germany (€)": price_in_de})
    
# Converting the list of dictionaries in to a Pandas DataFrame    

ev_df = pd.DataFrame(ev_data)


# Print the head of the dataframe to check structure and check dataframe shape

print(ev_df.head())

print(ev_df.shape)

# Check the DataFrame info

print(ev_df.info())

                                  Make                          Model  \
0  Tesla Model 3 Long Range Dual Motor  Model 3 Long Range Dual Motor
1                      BMW i4 eDrive40                    i4 eDrive40
2                       Tesla Model 3                        Model 3
3                Dacia Spring Electric                Spring Electric
4                           Kia EV6 GT                         EV6 GT

  Battery_(Kwh) Acceleration_in_Secs_(1-100) Top_Speed_(km/h) Range_(km)  \
0            75                      4.4 sec         233 km/h     485 km
1          80.7                      5.7 sec         190 km/h     470 km
2          57.5                      6.1 sec         225 km/h     380 km
3          26.8                     15.0 sec         125 km/h     170 km
4          72.5                      3.5 sec         260 km/h     360 km

  Efficiency_(Wh/km) Price_in_Germany (€)
0          155 Wh/km              €60,260
1          172 Wh/km              €58,300
2          151 Wh/km              €48,260
3          158 Wh/km              €20,490
4          201 Wh/km              €65,990
(228, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228 entries, 0 to 227
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Make                          228 non-null    object
 1   Model                         228 non-null    object
 2   Battery_(Kwh)                 228 non-null    object
 3   Acceleration_in_Secs_(1-100)  228 non-null    object
 4   Top_Speed_(km/h)              228 non-null    object
 5   Range_(km)                    228 non-null    object
 6   Efficiency_(Wh/km)            228 non-null    object
 7   Price_in_Germany (€)          228 non-null    object
dtypes: object(8)
memory usage: 14.4+ KB
None

In [211]:
# Stripping out extraneous text from dataframe columns to facilitate analysis later

ev_df['Acceleration_in_Secs_(1-100)'] = ev_df['Acceleration_in_Secs_(1-100)'].str.replace("sec","")

ev_df['Top_Speed_(km/h)'] = ev_df['Top_Speed_(km/h)'].str.replace(" km/h","")

ev_df['Range_(km)'] = ev_df['Range_(km)'].str.replace(" km","")

ev_df['Efficiency_(Wh/km)'] = ev_df['Efficiency_(Wh/km)'].str.replace(" Wh/km", "")

ev_df['Price_in_Germany (€)'] = ev_df['Price_in_Germany (€)'].str.replace("€", "")

ev_df['Price_in_Germany (€)'] = ev_df['Price_in_Germany (€)'].str.replace(",", "")

ev_df['Price_in_Germany (€)'] = ev_df['Price_in_Germany (€)'].str.replace("*", "")

ev_df['Price_in_Germany (€)'] = ev_df['Price_in_Germany (€)'].str.replace("N/A", "")

print(ev_df.head())  

print(ev_df.info())

                                  Make                          Model  \
0  Tesla Model 3 Long Range Dual Motor  Model 3 Long Range Dual Motor
1                      BMW i4 eDrive40                    i4 eDrive40
2                       Tesla Model 3                        Model 3
3                Dacia Spring Electric                Spring Electric
4                           Kia EV6 GT                         EV6 GT

  Battery_(Kwh) Acceleration_in_Secs_(1-100) Top_Speed_(km/h) Range_(km)  \
0            75                         4.4               233        485
1          80.7                         5.7               190        470
2          57.5                         6.1               225        380
3          26.8                        15.0               125        170
4          72.5                         3.5               260        360

  Efficiency_(Wh/km) Price_in_Germany (€)
0                155                60260
1                172                58300
2                151                48260
3                158                20490
4                201                65990
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228 entries, 0 to 227
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Make                          228 non-null    object
 1   Model                         228 non-null    object
 2   Battery_(Kwh)                 228 non-null    object
 3   Acceleration_in_Secs_(1-100)  228 non-null    object
 4   Top_Speed_(km/h)              228 non-null    object
 5   Range_(km)                    228 non-null    object
 6   Efficiency_(Wh/km)            228 non-null    object
 7   Price_in_Germany (€)          228 non-null    object
dtypes: object(8)
memory usage: 14.4+ KB
None

C:\Users\keneb\AppData\Local\Temp/ipykernel_26492/2611192649.py:15: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  ev_df['Price_in_Germany (€)'] = ev_df['Price_in_Germany (€)'].str.replace("*", "")

In [212]:
# converting objects to numeric values where possible to facilitate analysis later

cols = ev_df.columns.drop(['Make' , 'Model'])

ev_df[cols]=ev_df[cols].apply(pd.to_numeric, errors='ignore')

print(ev_df.info())
print(ev_df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228 entries, 0 to 227
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Make                          228 non-null    object
 1   Model                         228 non-null    object
 2   Battery_(Kwh)                 228 non-null    float64
 3   Acceleration_in_Secs_(1-100)  228 non-null    float64
 4   Top_Speed_(km/h)              228 non-null    int64
 5   Range_(km)                    228 non-null    int64
 6   Efficiency_(Wh/km)            228 non-null    int64
 7   Price_in_Germany (€)          214 non-null    float64
dtypes: float64(3), int64(3), object(2)
memory usage: 14.4+ KB
None
                                  Make                          Model  \
0  Tesla Model 3 Long Range Dual Motor  Model 3 Long Range Dual Motor
1                      BMW i4 eDrive40                    i4 eDrive40
2                       Tesla Model 3                        Model 3
3                Dacia Spring Electric                Spring Electric
4                           Kia EV6 GT                         EV6 GT

   Battery_(Kwh)  Acceleration_in_Secs_(1-100)  Top_Speed_(km/h)  Range_(km)  \
0           75.0                           4.4               233         485
1           80.7                           5.7               190         470
2           57.5                           6.1               225         380
3           26.8                          15.0               125         170
4           72.5                           3.5               260         360

   Efficiency_(Wh/km)  Price_in_Germany (€)
0                 155               60260.0
1                 172               58300.0
2                 151               48260.0
3                 158               20490.0
4                 201               65990.0

In [213]:
#checking for non numeric values in Price column

price_list=ev_df['Price_in_Germany (€)'].tolist()
            
print(price_list)

[60260.0, 58300.0, 48260.0, 20490.0, 65990.0, 48900.0, 106374.0, 50970.0, 35350.0, 59965.0, 47541.0, 44750.0, 48990.0, 98000.0, 69900.0, 55000.0, 41850.0, 39000.0, 41700.0, 33850.0, 39090.0, 135529.0, 66965.0, 37990.0, 35450.0, 150000.0, 31990.0, 47500.0, 52890.0, 115000.0, 50000.0, 55000.0, 150000.0, 31950.0, 27560.0, 34490.0, 45100.0, 29990.0, 70626.0, 138200.0, 37550.0, 48500.0, 77300.0, 57989.0, 44450.0, 57650.0, 47490.0, 35993.0, 66069.0, 67300.0, 35460.0, 45080.0, 29900.0, 39650.0, 150000.0, 54475.0, 44300.0, 77300.0, nan, 37220.0, 57700.0, 50415.0, 63700.0, 47550.0, 41900.0, 41900.0, 24790.0, 34640.0, 59990.0, 85000.0, 26895.0, 33990.0, 34110.0, 46495.0, 186336.0, 56150.0, 47000.0, 47000.0, 132200.0, 50990.0, 49500.0, 35650.0, 62560.0, 33990.0, 125000.0, 34600.0, 29990.0, 36960.0, 47500.0, 32500.0, 42620.0, 38490.0, 44990.0, 160000.0, 53615.0, 53600.0, nan, 42700.0, 35200.0, 71388.0, 152546.0, 19120.0, 99800.0, 81500.0, 37790.0, 55311.0, nan, 23560.0, 30560.0, 48850.0, 42600.0, 36950.0, 46515.0, 42460.0, nan, 29560.0, 106487.0, 47550.0, 97806.0, 45000.0, nan, 60000.0, 103827.0, nan, 56216.0, 28500.0, 55900.0, 35290.0, 38000.0, 49000.0, 55600.0, 85543.0, 53538.0, 91267.0, 72900.0, 50900.0, nan, 39440.0, 100000.0, 38990.0, 32700.0, 50000.0, 55960.0, 38450.0, 53000.0, 95658.0, 18460.0, 42990.0, 54750.0, 65000.0, 36590.0, 38600.0, 131834.0, 52342.0, 43900.0, 45700.0, 112009.0, 153016.0, 83750.0, 93800.0, nan, 33990.0, 64530.0, 69100.0, 37590.0, 60625.0, 120000.0, 56370.0, 42000.0, 71010.0, 71350.0, 187746.0, 96050.0, 72281.0, 56190.0, 38100.0, 42590.0, 65385.0, 21720.0, 187288.0, 42400.0, 64248.0, 65140.0, 58230.0, 57440.0, 51440.0, 60678.0, 132786.0, 41040.0, 56980.0, 86495.0, 57440.0, 111842.0, 56228.0, 56190.0, 56980.0, 59385.0, 59800.0, 50190.0, 92219.0, nan, 61571.0, 58530.0, 154444.0, nan, 67818.0, 56690.0, 112961.0, 107439.0, 68711.0, 58230.0, 51111.0, nan, nan, 54625.0, nan, 153968.0, 50980.0, 52230.0, nan, 50278.0, 56700.0, 50880.0, 50880.0, 57061.0, 50980.0, 50190.0, 53800.0]

In [221]:
# Converting Price from a string to a float

ev_df['Price_in_Germany (€)'] = ev_df['Price_in_Germany (€)'].apply(pd.to_numeric, errors = 'coerce')

print(price_list)

[60260.0, 58300.0, 48260.0, 20490.0, 65990.0, 48900.0, 106374.0, 50970.0, 35350.0, 59965.0, 47541.0, 44750.0, 48990.0, 98000.0, 69900.0, 55000.0, 41850.0, 39000.0, 41700.0, 33850.0, 39090.0, 135529.0, 66965.0, 37990.0, 35450.0, 150000.0, 31990.0, 47500.0, 52890.0, 115000.0, 50000.0, 55000.0, 150000.0, 31950.0, 27560.0, 34490.0, 45100.0, 29990.0, 70626.0, 138200.0, 37550.0, 48500.0, 77300.0, 57989.0, 44450.0, 57650.0, 47490.0, 35993.0, 66069.0, 67300.0, 35460.0, 45080.0, 29900.0, 39650.0, 150000.0, 54475.0, 44300.0, 77300.0, nan, 37220.0, 57700.0, 50415.0, 63700.0, 47550.0, 41900.0, 41900.0, 24790.0, 34640.0, 59990.0, 85000.0, 26895.0, 33990.0, 34110.0, 46495.0, 186336.0, 56150.0, 47000.0, 47000.0, 132200.0, 50990.0, 49500.0, 35650.0, 62560.0, 33990.0, 125000.0, 34600.0, 29990.0, 36960.0, 47500.0, 32500.0, 42620.0, 38490.0, 44990.0, 160000.0, 53615.0, 53600.0, nan, 42700.0, 35200.0, 71388.0, 152546.0, 19120.0, 99800.0, 81500.0, 37790.0, 55311.0, nan, 23560.0, 30560.0, 48850.0, 42600.0, 36950.0, 46515.0, 42460.0, nan, 29560.0, 106487.0, 47550.0, 97806.0, 45000.0, nan, 60000.0, 103827.0, nan, 56216.0, 28500.0, 55900.0, 35290.0, 38000.0, 49000.0, 55600.0, 85543.0, 53538.0, 91267.0, 72900.0, 50900.0, nan, 39440.0, 100000.0, 38990.0, 32700.0, 50000.0, 55960.0, 38450.0, 53000.0, 95658.0, 18460.0, 42990.0, 54750.0, 65000.0, 36590.0, 38600.0, 131834.0, 52342.0, 43900.0, 45700.0, 112009.0, 153016.0, 83750.0, 93800.0, nan, 33990.0, 64530.0, 69100.0, 37590.0, 60625.0, 120000.0, 56370.0, 42000.0, 71010.0, 71350.0, 187746.0, 96050.0, 72281.0, 56190.0, 38100.0, 42590.0, 65385.0, 21720.0, 187288.0, 42400.0, 64248.0, 65140.0, 58230.0, 57440.0, 51440.0, 60678.0, 132786.0, 41040.0, 56980.0, 86495.0, 57440.0, 111842.0, 56228.0, 56190.0, 56980.0, 59385.0, 59800.0, 50190.0, 92219.0, nan, 61571.0, 58530.0, 154444.0, nan, 67818.0, 56690.0, 112961.0, 107439.0, 68711.0, 58230.0, 51111.0, nan, nan, 54625.0, nan, 153968.0, 50980.0, 52230.0, nan, 50278.0, 56700.0, 50880.0, 50880.0, 57061.0, 50980.0, 50190.0, 53800.0]

In [222]:
print(ev_df.info())
print(ev_df.head(20))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228 entries, 0 to 227
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Make                          228 non-null    object
 1   Model                         228 non-null    object
 2   Battery_(Kwh)                 228 non-null    float64
 3   Acceleration_in_Secs_(1-100)  228 non-null    float64
 4   Top_Speed_(km/h)              228 non-null    int64
 5   Range_(km)                    228 non-null    int64
 6   Efficiency_(Wh/km)            228 non-null    int64
 7   Price_in_Germany (€)          214 non-null    float64
dtypes: float64(3), int64(3), object(2)
memory usage: 14.4+ KB
None
                                   Make                          Model  \
0   Tesla Model 3 Long Range Dual Motor  Model 3 Long Range Dual Motor
1                       BMW i4 eDrive40                    i4 eDrive40
2                        Tesla Model 3                        Model 3
3                 Dacia Spring Electric                Spring Electric
4                            Kia EV6 GT                         EV6 GT
5        Hyundai IONIQ 5 Long Range AWD         IONIQ 5 Long Range AWD
6                     Mercedes EQS 450+                       EQS 450+
7      Polestar 2 Long Range Dual Motor        2 Long Range Dual Motor
8                Hyundai IONIQ Electric                 IONIQ Electric
9   Tesla Model Y Long Range Dual Motor  Model Y Long Range Dual Motor
10                     Mercedes EQA 250                        EQA 250
11                    Skoda Enyaq iV 80                    Enyaq iV 80
12               Kia EV6 Long Range 2WD             EV6 Long Range 2WD
13                      BMW iX xDrive50                    iX xDrive50
14                           BMW i4 M50                         i4 M50
15                   Nissan Ariya 87kWh                    Ariya 87kWh
16         Hyundai Kona Electric 64 kWh           Kona Electric 64 kWh
17                        BMW i3 120 Ah                      i3 120 Ah
18     Renault Megane E-Tech EV60 220hp       Megane E-Tech EV60 220hp
19                             Honda e                              e

    Battery_(Kwh)  Acceleration_in_Secs_(1-100)  Top_Speed_(km/h)  Range_(km)  \
0            75.0                           4.4               233         485
1            80.7                           5.7               190         470
2            57.5                           6.1               225         380
3            26.8                          15.0               125         170
4            72.5                           3.5               260         360
5            70.0                           5.2               185         370
6           107.8                           6.2               210         640
7            75.0                           4.7               205         395
8            38.3                           9.7               165         250
9            75.0                           5.0               217         435
10           66.5                           8.9               160         355
11           77.0                           8.6               160         420
12           72.5                           7.3               185         400
13          105.2                           4.6               200         505
14           80.7                           3.9               225         435
15           87.0                           7.6               160         445
16           64.0                           7.9               167         395
17           37.9                           7.3               150         235
18           60.0                           7.5               160         360
19           28.5                           9.0               145         170

    Efficiency_(Wh/km)  Price_in_Germany (€)
0                  155               60260.0
1                  172               58300.0
2                  151               48260.0
3                  158               20490.0
4                  201               65990.0
5                  189               48900.0
6                  168              106374.0
7                  190               50970.0
8                  153               35350.0
9                  172               59965.0
10                 187               47541.0
11                 183               44750.0
12                 181               48990.0
13                 208               98000.0
14                 186               69900.0
15                 196               55000.0
16                 162               41850.0
17                 161               39000.0
18                 167               41700.0
19                 168               33850.0

In [224]:
# Preliminary analysis

print("The median battery capacity is "+  str(ev_df['Battery_(Kwh)'].median()) + "Kwh."'\n')

print("The car with the highest battery capacity is the "+ ev_df.loc[ev_df['Battery_(Kwh)'].idxmax(),'Make'] + " at " + str(ev_df['Battery_(Kwh)'].max()) + "Kwh."'\n')

print("The car with the highest battery capacity is the "+ ev_df.loc[ev_df['Battery_(Kwh)'].idxmin(),'Make'] + " at " + str(ev_df['Battery_(Kwh)'].min()) + "Kwh."'\n')

print("The median range is " + str(ev_df['Range_(km)'].median()) +"km"'\n')

print("The car with the longest range is the "+ ev_df.loc[ev_df['Range_(km)'].idxmax(),'Make'] + " at " + str(ev_df['Range_(km)'].max()) + "km."'\n')

print("The car with the shortest range is the "+ ev_df.loc[ev_df['Range_(km)'].idxmin(),'Make'] + " at " + str(ev_df['Range_(km)'].min()) + "km."'\n')

print("The median energy efficiency is " + str(ev_df['Efficiency_(Wh/km)'].median()) +" Wh/km"'\n')

print("The most energy efficient car is the "+ ev_df.loc[ev_df['Efficiency_(Wh/km)'].idxmin(),'Make'] + " at " + str(ev_df['Efficiency_(Wh/km)'].min()) + "Wh/km."'\n')

print("The least energy efficient car is the "+ ev_df.loc[ev_df['Efficiency_(Wh/km)'].idxmax(),'Make'] + " at " + str(ev_df['Efficiency_(Wh/km)'].max()) + "Wh/km."'\n')

print("The median acceleration rate from 0 to 100 km/h is " + str(ev_df['Acceleration_in_Secs_(1-100)'].median()) + "sec"'\n')

print("The car with the fastest acceleration is the "+ ev_df.loc[ev_df['Acceleration_in_Secs_(1-100)'].idxmin(),'Make'] + " at " + str(ev_df['Acceleration_in_Secs_(1-100)'].min()) + "secs."'\n')

print("The car with the slowest acceleration is the "+ ev_df.loc[ev_df['Acceleration_in_Secs_(1-100)'].idxmax(),'Make'] + " at " + str(ev_df['Acceleration_in_Secs_(1-100)'].max()) + "secs."'\n')

print("The median top speed is " + str(ev_df['Top_Speed_(km/h)'].median()) + "km/h"'\n')

print("The car capable of the highest speed is the "+ ev_df.loc[ev_df['Top_Speed_(km/h)'].idxmax(),'Make'] + " at " + str(ev_df['Top_Speed_(km/h)'].max()) + "km/h."'\n')

print("The car with the lowest maximum speed is the "+ ev_df.loc[ev_df['Top_Speed_(km/h)'].idxmin(),'Make'] + " at " + str(ev_df['Top_Speed_(km/h)'].min()) + "km/h."'\n')

print("The median price for an electric car in Germany is €" + str(int(ev_df['Price_in_Germany (€)'].median())) + '\n')

print("The most expensive car is the "+ ev_df.loc[ev_df['Price_in_Germany (€)'].idxmax(),'Make'] + " at €" + str(int(ev_df['Price_in_Germany (€)'].max()))+'\n')

print("The least expensive car is the "+ ev_df.loc[ev_df['Price_in_Germany (€)'].idxmin(),'Make'] + " at €" + str(int(ev_df['Price_in_Germany (€)'].min()))+'\n')

The median battery capacity is 66.5Kwh.

The car with the highest battery capacity is the Mercedes EQS 450+ at 107.8Kwh.

The car with the highest battery capacity is the Smart EQ forfour  at 16.7Kwh.

The median range is 337.5km

The car with the longest range is the Mercedes EQS 450+ at 640km.

The car with the shortest range is the Smart EQ forfour  at 95km.

The median energy efficiency is 190.0 Wh/km

The most energy efficient car is the Lightyear One  at 104Wh/km.

The least energy efficient car is the Mercedes EQV 300 Long at 295Wh/km.

The median acceleration rate from 0 to 100 km/h is 7.95sec

The car with the fastest acceleration is the Tesla Model S Plaid at 2.1secs.

The car with the slowest acceleration is the Dacia Spring Electric at 15.0secs.

The median top speed is 160.0km/h

The car capable of the highest speed is the Tesla Model S Plaid at 322km/h.

The car with the lowest maximum speed is the Dacia Spring Electric at 125km/h.

The median price for an electric car in Germany is €52616

The most expensive car is the Porsche Taycan Turbo S Cross Turismo at €187746

The least expensive car is the Smart EQ fortwo coupe at €18460

In [189]:
#exporting dataframe to csv
ev_df.to_csv('ev_df.csv', index=True)

In [225]:
import matplotlib.pyplot as plt
import seaborn as sns